### ISSUE TITLE
Embed PDF into company's application view of candidate

### ISSUE THREAD

**Issue by acron0** [WorksHub/client#48]
We would quite like to have a candidate's CV embedded beneath their "current application" section on their profile when viewed from a company perspective. In the past there were tools like `pdf.js` to achieve this but we were reluctant to introduce these. However, we now we believe browser support for PDFs to be good enough that [we can simply use an iframe](https://www.w3docs.com/tools/code-editor/1085) instead. **This should only be shown if the document is in the PDF format!**

![image](https://user-images.githubusercontent.com/812199/100358375-048cf280-2fee-11eb-93c3-7d7675f47563.png)

Steps to get to this screen:
 * Follow instructions to set up app from [here](https://github.com/WorksHub/client#getting-started)
 * Click 'Login'
 * Login as `company@example.com`
 * Hover 'Jobs' and click 'All live Applications' 
 * Click 'Candidate User' on the application beneath 'Junior Maker of Everything' 

Please don't hesitate to ask questions here.

**Comment by Iiqbal2000** [comment]
when I logged in using a company account, then I returned to being an anonymous user not a company user.

**Comment by acron0** [comment]
> when I logged in using a company account, then I returned to being an anonymous user not a company user.

I will fix this and re-open this issue when it's re-opened

**Comment by acron0** [comment]
Ok, should be fixed now. @Iiqbal2000

**Comment by jcwii** [comment]
@acron0 embedded beneath the "Applications" div and above the "Activity & Stats" div, in it's own div with a similar white background containing the iframe? In this case I envision that when View CV is clicked, the Activity & Stats div shifts down and another div appears between that and Applications.

Alternatively, would you consider an iframe with a z-index greater than all other content, clearly showing a close button? In effect, an on-page popup... my gut says to go this route since PDFs would be less constrained by any set div widths, and in turn would utilize screen width well.

Let me know what you have in mind, or maybe @liqbal2000 is already close to a solution? Wouldn't want to duplicate efforts, thanks all!

**Comment by jcwii** [comment]
@acron0 embedded beneath the "Applications" div and above the "Activity & Stats" div, in it's own div with a similar white background containing the iframe? In this case I envision that when View CV is clicked, the Activity & Stats div shifts down and another div appears between that and Applications.

Alternatively, would you consider an iframe with a z-index greater than all other content, clearly showing a close button? In effect, an on-page popup... my gut says to go this route since PDFs would be less constrained by any set div widths, and in turn would utilize screen width well.

Let me know what you have in mind, or maybe @Iiqbal2000 is already close to a solution? Wouldn't want to duplicate efforts, thanks all!

**Comment by Iiqbal2000** [comment]
I got error

**Comment by codeR49** [comment]
I want to have a shot

**Comment by acron0** [comment]
> I want to have a shot

@codeR49 Visit https://www.works-hub.com/issue/9ce98667-5f1d-40b2-ba11-01459586c230 and click 'Start Work' !

**Comment by acron0** [comment]
> I got error

@Iiqbal2000 What error are you having?

**Comment by acron0** [comment]
> @acron0 embedded beneath the "Applications" div and above the "Activity & Stats" div, in it's own div with a similar white background containing the iframe? In this case I envision that when View CV is clicked, the Activity & Stats div shifts down and another div appears between that and Applications.
> 
> Alternatively, would you consider an iframe with a z-index greater than all other content, clearly showing a close button? In effect, an on-page popup... my gut says to go this route since PDFs would be less constrained by any set div widths, and in turn would utilize screen width well.
> 
> Let me know what you have in mind, or maybe @Iiqbal2000 is already close to a solution? Wouldn't want to duplicate efforts, thanks all!

@jcwii I'm open-minded about design. I like to see what people come up with, so long as it generally fits in with our style guide. Re modal, again, I am open-minded so long as it's elegant (@yanisurbis might have other opinions about modals!). Bear in mind, we want to keep some mechanism for being able to download/access the CV outside of the embed as well, as some clients will want to upload the CV into their own ATS.

**Comment by jcwii** [comment]
@acron0 modal is absolutely the word I was looking for! Since a few others are looking into it at this time, I will remain in tow and excited to see what they come up with, thank you!

**Comment by giovanialtelino** [comment]
I would like some quick thoughts about it:

![Screenshot from 2021-01-04 14-44-39](https://user-images.githubusercontent.com/50564867/103563492-9f090d00-4e9b-11eb-81e6-ab0a97f530d8.png)

The CV section would be hidden by default, and a "Download CV" link would be added so the person could easily download the .pdf file. Would need to add another data to the re-frame db, something like :cv-visible which would switch the "Hide CV"/"View CV" and the section visibility.
The CV section would also have a bigger height than in the image.

And about the "This should only be shown if the document is in the PDF format!", could I rely the file name?
For example if the file ends with .pdf I can consider it as a pdf, just to be sure if you are checking the mime type in the back-end.
In the example above I'm using a random .pdf that I found public.

**Comment by acron0** [comment]
@giovanialtelino Looks great and your ideas sound like they would work as well. And yes, I think the file extension is probably accurate enough to use at this stage. Thanks!

**Comment by giovanialtelino** [comment]
Hello again, sorry the delay, but I guess the issue is still open since no one commented...
I think I'm almost done, but I'm having just an issue now that I'm testing, the graphQL API returns the relative path of the CV instead of the absolute path, them the iFrame open is a link to another localhost page that doesn't exists, since it merges the relative path with the current path which is "localhost".

![Screenshot_2021-01-15 Candidate User Functional Works(5)](https://user-images.githubusercontent.com/50564867/104766819-f172e500-5749-11eb-8793-6dadeb1bd681.png)

Here is the example if I set the absolute path

![Screenshot_2021-01-15 Candidate User Functional Works(4)](https://user-images.githubusercontent.com/50564867/104766809-ed46c780-5749-11eb-850d-a79d2a7e6eda.png)

The public view os the profile is kept the same

![Screenshot_2021-01-15 Candidate User Functional Works](https://user-images.githubusercontent.com/50564867/104766869-09e2ff80-574a-11eb-9b40-11cde58293d2.png)

Not sure if I can push it to you guys have a look.

**Comment by acron0** [comment]
@giovanialtelino Hi, really sorry about the delay to your question! Were you able to progress any further with this?

**Comment by giovanialtelino** [comment]
Ey @acron0 , I had forgotten about it.
Well, I think it's fine besides the "section-cv" size, I'm not figuring out how to change its height.
I'm submitting the PR, but it seems a lot of static build went together with it.

**Comment by acron0** [comment]
@giovanialtelino Oh no! Really hope you can resurrect it...we haven't had any other PRs for this despite a lot of interest so keen to see what you ahve

**Comment by giovanialtelino** [comment]
@acron0 , just managed to do it, I did a not ideal command... "git pull +:cv"
I was supposed to copy the commit code before the : to go back to a previous commit, but didn't copied it and pressed enter too quickly to see....
Well, happily the code was still locally avaliable in my computer, I deleted my old fork, forked a new one and just opened the PR.
