### ISSUE TITLE
Clicking on the label next to checkboxes does not check/uncheck the corresponding checkbox.

### ISSUE THREAD

**Issue by lacogubik** [WorksHub/client#7]
## Steps to reproduce
- Open an incognito session without any extensions
- Log in as candidate and navigate to job board `/jobs`
- In filter section try to select some checkbox by clicking on the label next to it

## Expected result
The checkbox should be selected

## Actual result
The checkbox is not selected

## Notes
There is single component in `wh.components.forms.views/labelled-checkbox` which is used for all the checkboxes.

**Comment by tolgraven** [comment]
So I tried to have a look at this specifically, but given the size of the app layout it turned into exploration. Interesting! There's certainly a lot going on but also a fair bit of overlap and duplication hey.
Things feel real far apart. Though that's obviously the point...
My style being the exact opposite, and knowing I definitely need to learn to veer this direction if I'm to write grown-up billable code, so with open mind still but still a lot of wondering like, at which point does further compartmentalization mostly just make things devolve?

Anyways. Someone having nicked the <label> for use as replacement checkbox, I started swapping things around to try and see how could work it out without throwing an event handler at it, but nothing happened. Turns out there are multiple sass files and doubled up definitions.

A sassy parable? I don't know.
